sudo: required
language: generic 

services:
  - docker

before_install:
- docker build -t itay19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itay19/react-test npm test

after_success:
  - docker build -t itay19/multi-client ./client
  - docker build -t itay19/multi-nginx ./nginx
  - docker build -t itay19/multi-server ./server
  - docker build -t itay19/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push itay19/multi-client
  - docker push itay19/multi-nginx
  - docker push itay19/multi-server
  - docker push itay19/multi-worker





